### ISSUE TITLE
Polymer 2 compatibility

### ISSUE THREAD

**Issue by Juravenator** [Juravenator/paper-dropdown-input#1]

**Comment by mcd1992** [comment]
Would love to get some 2.0 compatibility since your component is the only one that follows the material design format. I tested changing all dependencies in the bower.json to their 2.0 versions and didn't run into any errors. When testing though the paper-dropdown-input element didn't render at all but did show up in the DOM correctly. Might take a crack at it when I get time to read up on how it all works.

**Comment by Juravenator** [comment]
I'll soon have some time again to finally look into this subject. I will also use this opportunity to compare this element with the v2 version of paper-dropdown-menu, which it is closely related to.

That last part can potentially take some time. If you happen to find something to make it work already in Polymer v2, feel free to open a pull request, I will tag a new release so you can continue your work :)

**Comment by Juravenator** [comment]
Starting from release 2.5.0, Polymer support for paper-dropdown-input has shifted from `1.x` to `1.9 - 2`.
I have tested as much as I could in Polymer 2.0.1 and 1.9.3, and I will close this ticket for now.  
if you experience any Polymer 2 related issues, feel free to open a ticket for them or re-open this one if it seems appropriate.
